// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteShop.DAL.EF;

namespace NoteShop.DAL.Migrations
{
    [DbContext(typeof(NoteShopContext))]
    [Migration("20210204142245_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NoteShop.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("NoteShop.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 2,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 3,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 4,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 5,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 6,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 7,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 8,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 9,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 10,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 11,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 12,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 13,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 14,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 15,
                            Height = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = 16,
                            Height = 0,
                            Width = 0
                        });
                });

            modelBuilder.Entity("NoteShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NoteShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ImageId");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("NoteShop.Models.Diary", b =>
                {
                    b.HasBaseType("NoteShop.Models.Product");

                    b.Property<long>("StyleCover")
                        .HasColumnType("bigint");

                    b.ToTable("Diaries");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Count = 50,
                            ImageId = 8,
                            Name = "Diary Ranok",
                            Price = 35f,
                            StyleCover = 1L
                        },
                        new
                        {
                            Id = 9,
                            Count = 27,
                            ImageId = 9,
                            Name = "Diary Rozumniy",
                            Price = 50f,
                            StyleCover = 0L
                        },
                        new
                        {
                            Id = 10,
                            Count = 10,
                            ImageId = 10,
                            Name = "Diary Elite",
                            Price = 70f,
                            StyleCover = 2L
                        });
                });

            modelBuilder.Entity("NoteShop.Models.Notebook", b =>
                {
                    b.HasBaseType("NoteShop.Models.Product");

                    b.Property<long>("Murkup")
                        .HasColumnType("bigint");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.ToTable("Notebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 100,
                            ImageId = 1,
                            Name = "Notebook Poligraphist 12",
                            Price = 1f,
                            Murkup = 2L,
                            PageCount = 12,
                            Size = 1L
                        },
                        new
                        {
                            Id = 2,
                            Count = 190,
                            ImageId = 2,
                            Name = "Notebook Poligraphist 18",
                            Price = 1.25f,
                            Murkup = 0L,
                            PageCount = 18,
                            Size = 1L
                        },
                        new
                        {
                            Id = 3,
                            Count = 310,
                            ImageId = 3,
                            Name = "Notebook Poligraphist 12",
                            Price = 1.2f,
                            Murkup = 1L,
                            PageCount = 12,
                            Size = 1L
                        },
                        new
                        {
                            Id = 4,
                            Count = 70,
                            ImageId = 4,
                            Name = "Notebook 1st September 48",
                            Price = 15f,
                            Murkup = 2L,
                            PageCount = 48,
                            Size = 0L
                        },
                        new
                        {
                            Id = 5,
                            Count = 80,
                            ImageId = 5,
                            Name = "Notebook 1st September 18",
                            Price = 2.25f,
                            Murkup = 2L,
                            PageCount = 18,
                            Size = 1L
                        },
                        new
                        {
                            Id = 6,
                            Count = 150,
                            ImageId = 6,
                            Name = "Notebook 1st September 12",
                            Price = 1.2f,
                            Murkup = 2L,
                            PageCount = 12,
                            Size = 2L
                        },
                        new
                        {
                            Id = 7,
                            Count = 220,
                            ImageId = 7,
                            Name = "Notebook Poligraphist 24",
                            Price = 3.5f,
                            Murkup = 2L,
                            PageCount = 24,
                            Size = 0L
                        });
                });

            modelBuilder.Entity("NoteShop.Models.Pen", b =>
                {
                    b.HasBaseType("NoteShop.Models.Product");

                    b.Property<long>("Color")
                        .HasColumnType("bigint");

                    b.Property<float>("Thickness")
                        .HasColumnType("real");

                    b.ToTable("Pens");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Count = 100,
                            ImageId = 11,
                            Name = "Pen Pilot",
                            Price = 1f,
                            Color = 0L,
                            Thickness = 0.85f
                        },
                        new
                        {
                            Id = 12,
                            Count = 70,
                            ImageId = 12,
                            Name = "Pen MaxWriter",
                            Price = 4f,
                            Color = 1L,
                            Thickness = 0.5f
                        },
                        new
                        {
                            Id = 13,
                            Count = 40,
                            ImageId = 13,
                            Name = "Pen BIG",
                            Price = 5f,
                            Color = 2L,
                            Thickness = 0.75f
                        },
                        new
                        {
                            Id = 14,
                            Count = 70,
                            ImageId = 14,
                            Name = "Pen cells 10km",
                            Price = 15f,
                            Color = 3L,
                            Thickness = 0.65f
                        });
                });

            modelBuilder.Entity("NoteShop.Models.Pencil", b =>
                {
                    b.HasBaseType("NoteShop.Models.Product");

                    b.Property<long>("Hardness")
                        .HasColumnType("bigint");

                    b.ToTable("Pencils");

                    b.HasData(
                        new
                        {
                            Id = 15,
                            Count = 170,
                            ImageId = 15,
                            Name = "Pencil LowMarco",
                            Price = 2f,
                            Hardness = 2L
                        },
                        new
                        {
                            Id = 16,
                            Count = 200,
                            ImageId = 16,
                            Name = "Pencil Marco",
                            Price = 4f,
                            Hardness = 1L
                        });
                });

            modelBuilder.Entity("NoteShop.Models.Product", b =>
                {
                    b.HasOne("NoteShop.Models.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("NoteShop.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteShop.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("NoteShop.Models.Diary", b =>
                {
                    b.HasOne("NoteShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("NoteShop.Models.Diary", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteShop.Models.Notebook", b =>
                {
                    b.HasOne("NoteShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("NoteShop.Models.Notebook", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteShop.Models.Pen", b =>
                {
                    b.HasOne("NoteShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("NoteShop.Models.Pen", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteShop.Models.Pencil", b =>
                {
                    b.HasOne("NoteShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("NoteShop.Models.Pencil", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteShop.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NoteShop.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
